--select * from country where country like 'A%'and country like '%a';
--select * from country where country like '______' and country like '%h';
--select * from film where title ilike '%t%t%t%t';
--select * from film where title like 'C%' and length >90 and rental_rate =2.99;
